# Finansal Veriler

Python'un çok yönlülüğü, güçlü kütüphaneleriyle birleştiğinde, onu **finansal veri analizi** için en uygun dil haline getirir. 🏦🐍


Bu görevde, zaman içinde hisse senedi fiyatlarındaki dalgalanmaları görselleştirmeyi hedefliyoruz 📈📉.

## Veri keşfi

Finansal verileri bir `df` değişkenine yüklemek için aşağıdaki hücreyi çalıştırın.

In [1]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')
df.head()

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction
0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing
1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing
2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing
3,2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing
4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing

`.info()` yöntemini kullanarak veri türlerine göz atın.

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           506 non-null    object
 1   AAPL.Open      506 non-null    float64
 2   AAPL.High      506 non-null    float64
 3   AAPL.Low       506 non-null    float64
 4   AAPL.Close     506 non-null    float64
 5   AAPL.Volume    506 non-null    int64
 6   AAPL.Adjusted  506 non-null    float64
 7   dn             506 non-null    float64
 8   mavg           506 non-null    float64
 9   up             506 non-null    float64
 10  direction      506 non-null    object
dtypes: float64(8), int64(1), object(2)
memory usage: 43.6+ KB

Uygun işlevi kullanarak **istatistiksel bilgileri** görüntüleyin.

In [3]:
df.describe()

,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up
count,506.000000,506.000000,506.000000,506.000000,5.060000e+02,506.000000,506.000000,506.000000,506.000000
mean,112.935000,113.919447,111.942016,112.958340,4.317842e+07,110.459312,107.311385,112.739865,118.168345
std,11.287490,11.251892,11.263687,11.244744,1.985253e+07,10.537529,11.095804,10.595315,10.670752
min,90.000000,91.669998,89.470001,90.339996,1.147590e+07,89.008370,85.508858,94.047166,97.572721
25%,105.482500,106.349999,104.657501,105.672499,2.974240e+07,103.484803,97.011245,104.954875,111.052267
50%,112.889999,114.145001,111.800003,113.025002,3.747460e+07,110.821123,107.351628,112.799750,118.472542
75%,122.267498,123.497500,121.599998,122.179998,5.076395e+07,119.255457,114.812152,121.889416,128.515793
max,135.669998,136.270004,134.839996,135.509995,1.622063e+08,135.509995,127.289258,129.845000,138.805366

`Date` sütununu **datetime** formatına dönüştürün.

In [4]:
df["Date"]=pd.to_datetime(df["Date"])

Şimdi, `Date` sütununa daha yakından bakmamız gerekiyor.


Sürekli mi? Yoksa eksik günler var mı?


Veri kümesindeki haftanın her günü için satır sayısını sayın.


<details>
<summary>İpucu 🔍</summary>


- `.dayofweek` özniteliğini çağırarak bir tarih-saat nesnesinin haftanın gününü çıkarabilirsiniz.
- `value_counts()` yöntemi de size yardımcı olabilir (bkz. [belgeler](https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html))


</details>

In [5]:
df["Day_Name"] = df["Date"].dt.day_name()
df["Day_Name"].value_counts()

Day_Name
Tuesday      105
Wednesday    105
Thursday     103
Friday        99
Monday        94
Name: count, dtype: int64

Ne fark ettiniz?

> **Your Answer Here (Double click)**

Date sütununda `.isocalendar()` yöntemini kullanın. Bu yöntem ne tür bir nesne üretir?

In [6]:
df["Date"].dt.isocalendar()

     year  week  day
0    2015     8    2
1    2015     8    3
2    2015     8    4
3    2015     8    5
4    2015     9    1
..    ...   ...  ...
501  2017     6    5
502  2017     7    1
503  2017     7    2
504  2017     7    3
505  2017     7    4

[506 rows x 3 columns]

Ocak ve Aralık verilerini `df` ile filtrele

<details>
<summary> İpucu 🔍 </summary>


- Öncelikle, Tarih sütunundan `ay` değerini çıkarmanız gerekir
- Birden fazla değeri filtrelemek için Dataframe `.isin()` yöntemine bakın


</details>

In [7]:
df[(df['Date'].dt.month == 1) | (df['Date'].dt.month == 12)]

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction,Day_Name
200,2015-12-01,118.750000,118.809998,116.860001,117.339996,34852400,114.290588,112.795765,118.078000,123.360235,Decreasing,Tuesday
201,2015-12-02,117.339996,118.110001,116.080002,116.279999,33386600,113.258137,112.863291,117.806500,122.749709,Decreasing,Wednesday
202,2015-12-03,116.550003,116.790001,114.220001,115.199997,41569500,112.206202,112.900608,117.452667,122.004726,Decreasing,Thursday
203,2015-12-04,115.290001,119.250000,115.110001,119.029999,57777000,115.936671,113.069761,117.279333,121.488905,Increasing,Friday
204,2015-12-07,118.980003,119.860001,117.809998,118.279999,32084200,115.206161,113.278621,117.153666,121.028712,Decreasing,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...
489,2017-01-25,120.419998,122.099998,120.279999,121.879997,32377600,121.353858,115.170446,118.446500,121.722554,Increasing,Wednesday
490,2017-01-26,121.669998,122.440002,121.599998,121.940002,26337600,121.413604,115.123567,118.687000,122.250433,Increasing,Thursday
491,2017-01-27,122.139999,122.349998,121.599998,121.949997,20562900,121.423555,115.190236,118.935667,122.681098,Decreasing,Friday
492,2017-01-30,120.930000,121.629997,120.660004,121.629997,30377500,121.104937,115.423840,119.163667,122.903493,Increasing,Monday
493,2017-01-31,121.150002,121.389999,120.620003,121.349998,49201000,120.826147,115.850102,119.412167,122.974231,Increasing,Tuesday

## Yeniden örnekleme ve iadeler

`Date` sütununu indeks olarak ayarlayın.

In [8]:
df = df.set_index("Date")
df.head()

,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction,Day_Name
Date,,,,,,,,,,,
2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing,Tuesday
2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing,Wednesday
2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing,Thursday
2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing,Friday
2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing,Monday

**.resample()** işlevini kullanarak, her çeyrek için `AAPL.Open` minimum değerini ve `AAPL.Close` medyan değerini hesaplayın.

<details>
<summary> İpucu 🔍 </summary>


Birden fazla toplama işlevi uygulamak için `.agg()` yöntemini kullanabilirsiniz.


</details>

In [9]:
df.resample("Q").agg({"AAPL.Open": "min", "AAPL.Close": "median"})

/tmp/ipykernel_1119/336695200.py:1: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  df.resample("Q").agg({"AAPL.Open": "min", "AAPL.Close": "median"})

             AAPL.Open  AAPL.Close
Date
2015-03-31  122.309998  127.139999
2015-06-30  124.470001  127.599998
2015-09-30   94.870003  115.274998
2015-12-31  106.959999  114.365002
2016-03-31   93.129997   98.529999
2016-06-30   90.000000   97.635002
2016-09-30   94.599998  107.210003
2016-12-31  106.570000  113.540001
2017-03-31  115.800003  121.489998

`AAPL.Close` üzerinde `.pct_change()` yöntemini kullanarak günlük getirileri hesaplayın.

In [10]:
df['AAPL.Close'].pct_change()

Date
2015-02-17         NaN
2015-02-18    0.006962
2015-02-19   -0.002098
2015-02-20    0.008174
2015-02-23    0.027027
                ...
2017-02-10   -0.002266
2017-02-13    0.008856
2017-02-14    0.012979
2017-02-15    0.003629
2017-02-16   -0.001181
Name: AAPL.Close, Length: 506, dtype: float64

Bu kod satırı ne işe yarar?

In [11]:
df.resample("QS").first()[["AAPL.Open", "AAPL.Close"]].pct_change(4)

            AAPL.Open  AAPL.Close
Date
2015-01-01        NaN         NaN
2015-04-01        NaN         NaN
2015-07-01        NaN         NaN
2015-10-01        NaN         NaN
2016-01-01  -0.195153   -0.175859
2016-04-01  -0.128505   -0.114769
2016-07-01  -0.247518   -0.242575
2016-10-01   0.033373    0.026830
2017-01-01   0.128545    0.102515

> **Your Answer Here (Double click)**

Excel ile karşılaştırıldığında ne kadar zaman kazandığınızı bir düşünün! 🔥

`AAPL.Close`'un üç aylık ortalama değişimini hesaplayın.

In [12]:
df['AAPL.Close'].resample('QS').mean().pct_change()

Date
2015-01-01         NaN
2015-04-01    0.006952
2015-07-01   -0.083123
2015-10-01   -0.025609
2016-01-01   -0.128122
2016-04-01   -0.002547
2016-07-01    0.065038
2016-10-01    0.071155
2017-01-01    0.095504
Freq: QS-JAN, Name: AAPL.Close, dtype: float64

## Pencere(Window) işlevleri

`AAPL.Close`'un **son 4 gün** boyunca hareketli ortalamasını hesaplayın.

In [13]:
df['AAPL.Close'].rolling(4).mean()

Date
2015-02-17           NaN
2015-02-18           NaN
2015-02-19           NaN
2015-02-20    128.625000
2015-02-23    129.917499
                 ...
2017-02-10    132.027496
2017-02-13    132.467495
2017-02-14    133.212497
2017-02-15    133.984997
2017-02-16    134.792499
Name: AAPL.Close, Length: 506, dtype: float64

`.rolling()` yöntemi, sadece önceki satırların sayısını değil, bir zaman aralığını da belirlememizi sağlar. \
Bu, ilk satırlardaki NaN değerlerini ortadan kaldırmak için kullanışlıdır.


`AAPL.Close` değerinin hareketli ortalamasını **30 günlük bir kayan pencere kullanarak** hesaplayın.

In [14]:
df["AAPL.Close"].rolling("30D").mean()

Date
2015-02-17    127.830002
2015-02-18    128.275002
2015-02-19    128.333333
2015-02-20    128.625000
2015-02-23    129.500000
                 ...
2017-02-10    124.362856
2017-02-13    125.330998
2017-02-14    125.792379
2017-02-15    126.234089
2017-02-16    126.931817
Name: AAPL.Close, Length: 506, dtype: float64

## Kayıp değerler

Veri setimizde hafta sonu günleri eksik.


Dizin tarihlerindeki boşlukları doldurmak için DataFrame `.asfreq()` yöntemini kullanabiliriz. \
[Belgelere](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.asfreq.html) göz atın ve hafta sonu günlerini içeren `df_with_weekends` adlı yeni bir DataFrame oluşturun.

In [15]:
df_with_weekends = df.asfreq('D')
df_with_weekends.head(10)

,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction,Day_Name
Date,,,,,,,,,,,
2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400.0,122.905254,106.741052,117.927667,129.114281,Increasing,Tuesday
2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700.0,123.760965,107.842423,118.940333,130.038244,Increasing,Wednesday
2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400.0,123.501363,108.894245,119.889167,130.884089,Decreasing,Thursday
2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400.0,124.510914,109.785449,120.763500,131.741551,Increasing,Friday
2015-02-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-02-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100.0,127.876074,110.372516,121.720167,133.067817,Increasing,Monday
2015-02-24,132.940002,133.600006,131.169998,132.169998,69228100.0,127.078049,111.094869,122.664834,134.234798,Decreasing,Tuesday
2015-02-25,131.559998,131.600006,128.149994,128.789993,74711700.0,123.828261,113.211918,123.629667,134.047415,Decreasing,Wednesday
2015-02-26,128.789993,130.869995,126.610001,130.419998,91287500.0,125.395469,114.165299,124.282333,134.399367,Increasing,Thursday

`asfreq()` işlevi tarafından oluşturulan tüm NaN'leri ortadan kaldırmamız gerekiyor.


`fillna()` yöntemine [belgelere](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html#pandas.DataFrame.fillna) bakın ve bunu kullanarak eksik değerleri **bir sonraki geçerli değerle** değiştirin.


⚠️ Değeri `df_with_weekends`'e yeniden atamayın.

In [16]:
df_with_weekends.fillna(method='bfill')

/tmp/ipykernel_1119/2408565306.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_with_weekends.fillna(method='bfill')

,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction,Day_Name
Date,,,,,,,,,,,
2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400.0,122.905254,106.741052,117.927667,129.114281,Increasing,Tuesday
2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700.0,123.760965,107.842423,118.940333,130.038244,Increasing,Wednesday
2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400.0,123.501363,108.894245,119.889167,130.884089,Decreasing,Thursday
2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400.0,124.510914,109.785449,120.763500,131.741551,Increasing,Friday
2015-02-21,130.020004,133.000000,129.660004,133.000000,70974100.0,127.876074,110.372516,121.720167,133.067817,Increasing,Monday
...,...,...,...,...,...,...,...,...,...,...,...
2017-02-12,133.080002,133.820007,132.750000,133.289993,23035400.0,133.289993,114.820798,125.205166,135.589534,Increasing,Monday
2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400.0,133.289993,114.820798,125.205166,135.589534,Increasing,Monday
2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500.0,135.020004,115.175718,125.953499,136.731280,Increasing,Tuesday
2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600.0,135.509995,115.545035,126.723499,137.901963,Decreasing,Wednesday
2017-02-16,135.669998,135.899994,134.839996,135.350006,22118000.0,135.350006,116.203299,127.504333,138.805366,Decreasing,Thursday

Eksik değerleri değiştirmek için başka bir yöntem de [interpolasyon](https://en.wikipedia.org/wiki/Interpolation) kullanmaktır.


`interpolate()` yöntemine bakın ve eksik değerleri değiştirmek için kullanın. \
`df_with_weekends` değişkeninizi güncelleyebilirsiniz.

In [17]:
df_with_weekends = df_with_weekends.interpolate()
df_with_weekends.head(10)

/tmp/ipykernel_1119/2227106771.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_with_weekends = df_with_weekends.interpolate()

,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction,Day_Name
Date,,,,,,,,,,,
2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400.0,122.905254,106.741052,117.927667,129.114281,Increasing,Tuesday
2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700.0,123.760965,107.842423,118.940333,130.038244,Increasing,Wednesday
2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400.0,123.501363,108.894245,119.889167,130.884089,Decreasing,Thursday
2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400.0,124.510914,109.785449,120.763500,131.741551,Increasing,Friday
2015-02-21,129.086665,130.666667,128.586670,130.666667,56290300.0,125.632634,109.981138,121.082389,132.183640,NaN,NaN
2015-02-22,129.553334,131.833333,129.123337,131.833333,63632200.0,126.754354,110.176827,121.401278,132.625729,NaN,NaN
2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100.0,127.876074,110.372516,121.720167,133.067817,Increasing,Monday
2015-02-24,132.940002,133.600006,131.169998,132.169998,69228100.0,127.078049,111.094869,122.664834,134.234798,Decreasing,Tuesday
2015-02-25,131.559998,131.600006,128.149994,128.789993,74711700.0,123.828261,113.211918,123.629667,134.047415,Decreasing,Wednesday
2015-02-26,128.789993,130.869995,126.610001,130.419998,91287500.0,125.395469,114.165299,124.282333,134.399367,Increasing,Thursday

## Financial charts


Grafik oluşturma becerilerimizi geliştirme zamanı! 📈📉


Şu ana kadar, çalışmalarımızı yalnızca Apple hisselerine odakladık. Şimdi, birden fazla şirketin hisselerini de dahil ederek, yatırımcıların kararları için ihtiyaç duydukları temel grafikleri oluşturacağız.


**Python'un finans dünyasında neden bu kadar ün kazandığını keşfetmek üzeresiniz.** 🏦




<u>Not:</u> **Ticker**, belirli bir borsada belirli bir hisseyi belirtmek için kullanılan kısaltmadır (**ör.** Apple için *AAPL*, Tesla için *TSLA* vb.).


---








Birden fazla ticker'dan veri yüklemek için aşağıdaki hücreyi çalıştırın.


Değerlerin Day One'a göre yeniden bazlandığını unutmayın. Diğer bir deyişle, gördüğünüz şey orijinal ticker değeri değil, getiri değeridir.

In [18]:
df = px.data.stocks()

df["date"] = pd.to_datetime(df["date"], format='%Y-%m-%d', errors='coerce')
df = df.set_index("date")
df

                GOOG      AAPL      AMZN        FB      NFLX      MSFT
date
2018-01-01  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
2018-01-08  1.018172  1.011943  1.061881  0.959968  1.053526  1.015988
2018-01-15  1.032008  1.019771  1.053240  0.970243  1.049860  1.020524
2018-01-22  1.066783  0.980057  1.140676  1.016858  1.307681  1.066561
2018-01-29  1.008773  0.917143  1.163374  1.018357  1.273537  1.040708
...              ...       ...       ...       ...       ...       ...
2019-12-02  1.216280  1.546914  1.425061  1.075997  1.463641  1.720717
2019-12-09  1.222821  1.572286  1.432660  1.038855  1.421496  1.752239
2019-12-16  1.224418  1.596800  1.453455  1.104094  1.604362  1.784896
2019-12-23  1.226504  1.656000  1.521226  1.113728  1.567170  1.802472
2019-12-30  1.213014  1.678000  1.503360  1.098475  1.540883  1.788185

[105 rows x 6 columns]

`GOOG`'un gelişimini çizgi grafiği ile gösterin.

In [19]:
px.line(df, x=df.index, y='GOOG', title='GOOG Gelişimi')

GOOG'un minimum ve maksimum kümülatif değeri ile birlikte gelişimini **aynı grafikte** gösterin.

<details>
<summary>İpucu 🔍</summary>

- `cummin()` ve `cummax()` yöntemlerine bir göz atın.
- Plotly grafiğine bir çizgi eklemek için `.add_scatter()` yöntemini kullanabilirsiniz.

In [20]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=df.index, y=df['GOOG'], mode='lines', name='GOOG'))
fig.add_trace(go.Scatter(x=df.index, y=df['GOOG'].cummax(), mode='lines', name='Kümülatif Maksimum'))
fig.add_trace(go.Scatter(x=df.index, y=df['GOOG'].cummin(), mode='lines', name='Kümülatif Minimum'))
fig.update_layout(title='GOOG Gelişimi ile Kümülatif Min/Maks', xaxis_title='date', yaxis_title='GOOG')
fig.show()

GOOG'un gelişimini ve 10 günlük ve 30 günlük hareketli ortalamalarını **aynı grafikte** gösterin.

<details>
<summary>İpucu 🔍</summary>


burada `.rolling()` yöntemini kullanmak isteyebilirsiniz


</details>

In [21]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=df.index, y=df['GOOG'], mode='lines', name='GOOG'))
fig.add_trace(go.Scatter(x=df.index, y=df['GOOG'].rolling(10).mean(), mode='lines', name='10 Günlük Hareketli Ortalama'))
fig.add_trace(go.Scatter(x=df.index, y=df['GOOG'].rolling(30).mean(), mode='lines', name='30 Günlük Hareketli Ortalama'))
fig.update_layout(title='GOOG Gelişimi ile Hareketli Ortalamalar', xaxis_title='date', yaxis_title='GOOG')
fig.show()

___


Şimdi her bir ticker için getirileri ayrı grafiklerde göstereceğiz.

`pd.melt()` işlevi, geniş formatlı bir tabloyu daha uzun ve daha yapılandırılmış bir formata dönüştürebilir. \
Sütunlardan değişkenleri alır ve bunları satırlara dönüştürür, değişken adları için yeni bir sütun ve karşılık gelen değerler için başka bir sütun oluşturur.


Aşağıdaki hücreyi çalıştırın.

In [22]:
df_melt = pd.melt(df, var_name="ticker", ignore_index=False)
df_melt

           ticker     value
date
2018-01-01   GOOG  1.000000
2018-01-08   GOOG  1.018172
2018-01-15   GOOG  1.032008
2018-01-22   GOOG  1.066783
2018-01-29   GOOG  1.008773
...           ...       ...
2019-12-02   MSFT  1.720717
2019-12-09   MSFT  1.752239
2019-12-16   MSFT  1.784896
2019-12-23   MSFT  1.802472
2019-12-30   MSFT  1.788185

[630 rows x 2 columns]

Yeni oluşturulan DataFrame üzerinde `px.area()` işlevini kullanarak,


her bir ticker için **ayrı grafiklerde** getirileri görüntüleyin.

<details>
<summary> İpucu 🔍 </summary>

Ders notlarında çok benzer bir örnek gösterilmişti.


Şimdi `facet_col` komutunun ne işe yaradığını hatırlamanın tam zamanı!


</details>

In [23]:
px.area(df_melt, x=df_melt.index, y='value', facet_col='ticker', facet_col_wrap=3, title='Ticker Bazında Getiriler')